import { ToolDefinition } from "./types";

export const tools: ToolDefinition[] = [
  {
    id: "multi-angle-image",
    title: "8-Angle Visuals",
    shortDescription: "1 image -> 8 new campaign-ready perspectives",
    category: "product-visuals",
    inputMode: "single-image",
    outputMode: "image-gallery",
    status: "active",
    badge: "New",
    accepts: ["image/png", "image/jpeg", "image/webp"],
  },
  {
    id: "image-to-image",
    title: "Image to Image",
    shortDescription: "1 image + prompt -> stylized image variation",
    category: "product-visuals",
    inputMode: "single-image",
    outputMode: "image-gallery",
    status: "active",
    badge: "New",
    accepts: ["image/png", "image/jpeg", "image/webp"],
  },
  {
    id: "material-change",
    title: "Material Change",
    shortDescription: "Product image + material reference -> updated surface look",
    category: "product-visuals",
    inputMode: "multi-image",
    outputMode: "image-gallery",
    status: "active",
    badge: "New",
    accepts: ["image/png", "image/jpeg", "image/webp"],
  },
  {
    id: "six-frame-video",
    title: "6-Frame Motion",
    shortDescription: "6 frames -> 1 stylized video",
    category: "motion",
    inputMode: "multi-image-sequence",
    outputMode: "video",
    status: "active",
    badge: "Hot",
    accepts: ["image/png", "image/jpeg", "image/webp"],
  },
  {
    id: "image-to-video",
    title: "Image to Video",
    shortDescription: "1 image + motion settings -> generated video",
    category: "motion",
    inputMode: "single-image",
    outputMode: "video",
    status: "active",
    badge: "New",
    accepts: ["image/png", "image/jpeg", "image/webp"],
  },
  {
    id: "text-to-video",
    title: "Text to Video",
    shortDescription: "Prompt + timing settings -> generated motion video",
    category: "motion",
    inputMode: "text-plus-options",
    outputMode: "video",
    status: "active",
    badge: "New",
    accepts: [],
  },
  {
    id: "lip-sync",
    title: "Lip Sync",
    shortDescription: "Portrait + audio -> speaking video",
    category: "avatar-tools",
    inputMode: "image-plus-audio",
    outputMode: "video",
    status: "active",
    badge: "New",
    accepts: ["image/png", "image/jpeg", "image/webp", "audio/*"],
  },
  {
    id: "product-grid",
    title: "Product Grid",
    shortDescription: "1 product image -> stitched grid + tiles + upscale",
    category: "campaign-assets",
    inputMode: "single-image",
    outputMode: "image-gallery",
    status: "active",
    badge: "Premium",
    accepts: ["image/png", "image/jpeg", "image/webp"],
  },
];

export function getToolById(toolId: string) {
  return tools.find((tool) => tool.id === toolId);
}
