import { ToolDefinition } from "@/lib/tools/types";

export const tools: ToolDefinition[] = [
  {
    id: "multi-angle-image",
    title: "8-Angle Visuals",
    shortDescription: "1 image -> 8 fresh campaign-ready perspectives",
    longDescription:
      "Upload one image and generate eight new visual angles for ads, product storytelling, social content and fast concept validation.",
    category: "product-visuals",
    inputMode: "single-image",
    outputMode: "image-gallery",
    accepts: ["image/png", "image/jpeg", "image/webp"],
    minFiles: 1,
    maxFiles: 1,
    status: "active",
    badge: "Hot",
    isImplemented: true,
    generateRoute: "/api/generate-image",
    statusRouteBase: "/api/job-status",
    detailsRouteBase: "/api/job-details",
    outputRoute: "/api/output",
  },
  {
    id: "six-frame-video",
    title: "6-Frame Motion",
    shortDescription: "6 keyframes -> 1 stylized video",
    longDescription:
      "Upload six ordered frames and generate a motion clip. This tool exposes prompt, negative prompt, resolution, segment length, fps and output prefix so a marketer can tune the result without touching the workflow JSON.",
    category: "motion",
    inputMode: "multi-image-sequence",
    outputMode: "video",
    accepts: ["image/png", "image/jpeg", "image/webp"],
    minFiles: 6,
    maxFiles: 6,
    status: "active",
    badge: "New",
    isImplemented: true,
    generateRoute: "/api/tools/six-frame-video/generate",
    statusRouteBase: "/api/job-status",
    detailsRouteBase: "/api/job-details",
    outputRoute: "/api/output",
  },
  {
    id: "image-to-image",
    title: "Image to Image",
    shortDescription: "1 image + prompt -> stylized image variation",
    longDescription:
      "Upload one image, rewrite the prompt and generate a new visual variation with control over seed, guidance, megapixels, turbo mode and filename prefix.",
    category: "product-visuals",
    inputMode: "single-image",
    outputMode: "image-gallery",
    accepts: ["image/png", "image/jpeg", "image/webp"],
    minFiles: 1,
    maxFiles: 1,
    status: "active",
    badge: "New",
    isImplemented: true,
    generateRoute: "/api/tools/image-to-image/generate",
    statusRouteBase: "/api/job-status",
    detailsRouteBase: "/api/job-details",
    outputRoute: "/api/output",
  },
  {
    id: "icon-forge",
    title: "Icon Forge",
    shortDescription: "Prompt + style cues -> personalized icon pack",
    longDescription:
      "Generate branded icon sets for presentations, ads, landing pages and product explainers in a consistent visual language.",
    category: "campaign-assets",
    inputMode: "text-plus-options",
    outputMode: "image-gallery",
    accepts: [],
    minFiles: 0,
    maxFiles: 0,
    status: "beta",
    badge: "Premium",
    isImplemented: false,
    creditMode: "premium",
    creditCostNote:
      "This tool is premium and should consume extra user credits because it also burns extra credits on the Comfy side.",
  },
  {
    id: "product-grid",
    title: "Product Grid",
    shortDescription: "Multiple assets -> ready-to-use product composition",
    longDescription:
      "Assemble retail-friendly product grids and comparison layouts for e-commerce, distributors and campaign decks.",
    category: "product-visuals",
    inputMode: "mixed-input",
    outputMode: "image-gallery",
    accepts: ["image/png", "image/jpeg", "image/webp"],
    minFiles: 1,
    maxFiles: 12,
    status: "coming-soon",
    badge: "Soon",
    isImplemented: false,
  },
  {
    id: "text-to-video",
    title: "Text to Video",
    shortDescription: "Prompt -> short marketing video",
    longDescription:
      "Generate a short concept video from text for campaign ideation, fast pitch decks and social-first testing.",
    category: "motion",
    inputMode: "text-plus-options",
    outputMode: "video",
    accepts: [],
    minFiles: 0,
    maxFiles: 0,
    status: "coming-soon",
    badge: "Soon",
    isImplemented: false,
  },
  {
    id: "lip-sync",
    title: "Lip Sync",
    shortDescription: "Portrait + audio -> speaking video",
    longDescription:
      "Upload one portrait and one audio track to generate a talking character clip. This tool exposes text prompt, negative prompt, resize, fps, num frames, seed, steps, cfg and shift so the user can steer the speaking performance without editing the workflow.",
    category: "motion",
    inputMode: "mixed-input",
    outputMode: "video",
    accepts: ["image/png", "image/jpeg", "image/webp", "audio/mpeg", "audio/wav", "audio/mp3"],
    minFiles: 2,
    maxFiles: 2,
    status: "active",
    badge: "New",
    isImplemented: true,
    generateRoute: "/api/tools/lip-sync/generate",
    statusRouteBase: "/api/job-status",
    detailsRouteBase: "/api/job-details",
    outputRoute: "/api/output",
  },
  {
    id: "infinite-talk",
    title: "Infinite Talk",
    shortDescription: "Always-on talking avatar loops",
    longDescription:
      "Create continuous talking avatar outputs for product demos, onboarding snippets and avatar-driven communication flows.",
    category: "avatar-tools",
    inputMode: "mixed-input",
    outputMode: "video",
    accepts: ["image/png", "image/jpeg", "image/webp", "audio/mpeg", "audio/wav"],
    minFiles: 1,
    maxFiles: 3,
    status: "coming-soon",
    badge: "Soon",
    isImplemented: false,
  },
  {
    id: "image-to-video",
    title: "Image to Video",
    shortDescription: "Single visual -> animated motion clip",
    longDescription:
      "Convert a single image into a motion-ready short video for social posts, ads and quick hero section content.",
    category: "motion",
    inputMode: "single-image",
    outputMode: "video",
    accepts: ["image/png", "image/jpeg", "image/webp"],
    minFiles: 1,
    maxFiles: 1,
    status: "coming-soon",
    badge: "Soon",
    isImplemented: false,
  },
  {
    id: "scene-variants",
    title: "Scene Variants",
    shortDescription: "One visual -> multiple campaign scenes",
    longDescription:
      "Generate multiple scene interpretations from the same source visual to test mood, background and storytelling direction.",
    category: "product-visuals",
    inputMode: "single-image",
    outputMode: "image-gallery",
    accepts: ["image/png", "image/jpeg", "image/webp"],
    minFiles: 1,
    maxFiles: 1,
    status: "coming-soon",
    badge: "Soon",
    isImplemented: false,
  },
  {
    id: "social-pack",
    title: "Social Pack",
    shortDescription: "One concept -> multiple social asset variants",
    longDescription:
      "Turn one creative idea into a pack of assets for posts, stories, thumbnails and campaign previews.",
    category: "campaign-assets",
    inputMode: "mixed-input",
    outputMode: "asset-pack",
    accepts: ["image/png", "image/jpeg", "image/webp"],
    minFiles: 0,
    maxFiles: 8,
    status: "coming-soon",
    badge: "Soon",
    isImplemented: false,
  },
];

export const toolsById = new Map(tools.map((tool) => [tool.id, tool]));

export function getToolById(toolId: string) {
  return toolsById.get(toolId) ?? null;
}

export const toolCategories = [
  { id: "product-visuals", title: "Product visuals" },
  { id: "motion", title: "Motion" },
  { id: "campaign-assets", title: "Campaign assets" },
  { id: "avatar-tools", title: "Avatar tools" },
] as const;
