import { ToolDefinition } from "@/lib/tools/types";

const sharedJobRoutes = {
  statusRouteBase: "/api/job-status",
  detailsRouteBase: "/api/job-details",
  outputRoute: "/api/output",
} as const;

export const tools: ToolDefinition[] = [
  {
    id: "campaign-studio",
    title: "Campaign Studio",
    shortDescription: "Brief -> strategy -> campaign pack",
    longDescription: "Build a practical campaign strategy and execution pack from one guided marketing brief.",
    category: "campaign-ops",
    inputMode: "guided brief",
    outputMode: "strategy + copy pack",
    status: "beta",
    badge: "New",
    accepts: ["image/png", "image/jpeg", "image/webp", ".pdf", ".doc", ".docx"],
    creditMode: "standard",
    ...sharedJobRoutes,
  },
  {
    id: "multi-angle-image",
    title: "8-Angle Visuals",
    shortDescription: "1 image -> 8 new campaign-ready perspectives",
    longDescription: "Generate multiple product angles from a single source image.",
    category: "product-visuals",
    inputMode: "single-image",
    outputMode: "image-gallery",
    status: "active",
    badge: "New",
    accepts: ["image/png", "image/jpeg", "image/webp"],
    creditMode: "standard",
    generateRoute: "/api/generate-image",
    ...sharedJobRoutes,
  },
  {
    id: "image-to-image",
    title: "Image to Image",
    shortDescription: "1 image + prompt -> stylized image variation",
    longDescription: "Generate prompt-driven visual variations from one input image.",
    category: "product-visuals",
    inputMode: "single-image",
    outputMode: "image-gallery",
    status: "active",
    badge: "New",
    accepts: ["image/png", "image/jpeg", "image/webp"],
    creditMode: "standard",
    generateRoute: "/api/tools/image-to-image/generate",
    ...sharedJobRoutes,
  },
  {
    id: "inpaint-image",
    title: "Inpaint Image",
    shortDescription: "Image + mask -> replace selected region",
    longDescription: "Paint the area to replace directly in the browser.",
    category: "product-visuals",
    inputMode: "image-plus-mask",
    outputMode: "image-gallery",
    status: "active",
    badge: "New",
    accepts: ["image/png", "image/jpeg", "image/webp"],
    creditMode: "standard",
    generateRoute: "/api/tools/inpaint-image/generate",
    ...sharedJobRoutes,
  },
  {
    id: "outpaint",
    title: "Outpaint",
    shortDescription: "Extend image canvas into new space",
    longDescription: "Expand an image beyond its borders for new aspect ratios and layouts.",
    category: "product-visuals",
    inputMode: "single-image",
    outputMode: "image-gallery",
    status: "active",
    badge: "New",
    accepts: ["image/png", "image/jpeg", "image/webp"],
    creditMode: "standard",
    generateRoute: "/api/tools/outpaint/generate",
    ...sharedJobRoutes,
  },
  {
    id: "material-change",
    title: "Material Change",
    shortDescription: "Product image + material reference -> updated product finish",
    longDescription: "Swap materials or finishes using a product image and a material reference.",
    category: "product-visuals",
    inputMode: "two-images",
    outputMode: "image-gallery",
    status: "active",
    badge: "New",
    accepts: ["image/png", "image/jpeg", "image/webp"],
    creditMode: "standard",
    generateRoute: "/api/tools/material-change/generate",
    ...sharedJobRoutes,
  },
  {
    id: "product-mockup",
    title: "Product Mockup",
    shortDescription: "Design image + target image -> applied branded mockup",
    longDescription: "Apply a design reference to a target product or scene.",
    category: "campaign-assets",
    inputMode: "two-images",
    outputMode: "image-gallery",
    status: "active",
    badge: "New",
    accepts: ["image/png", "image/jpeg", "image/webp"],
    creditMode: "standard",
    generateRoute: "/api/tools/product-mockup/generate",
    ...sharedJobRoutes,
  },
  {
    id: "six-frame-video",
    title: "6-Frame Motion",
    shortDescription: "6 frames -> 1 stylized video",
    longDescription: "Turn six still frames into one stylized motion clip.",
    category: "motion",
    inputMode: "multi-image-sequence",
    outputMode: "video",
    status: "active",
    badge: "Hot",
    accepts: ["image/png", "image/jpeg", "image/webp"],
    creditMode: "standard",
    generateRoute: "/api/tools/six-frame-video/generate",
    ...sharedJobRoutes,
  },
  {
    id: "image-to-video",
    title: "Image to Video",
    shortDescription: "1 image + prompt -> generated motion clip",
    longDescription: "Animate a single still image into a short motion clip.",
    category: "motion",
    inputMode: "single-image",
    outputMode: "video",
    status: "active",
    badge: "New",
    accepts: ["image/png", "image/jpeg", "image/webp"],
    creditMode: "standard",
    generateRoute: "/api/tools/image-to-video/generate",
    ...sharedJobRoutes,
  },
  {
    id: "upscale-video",
    title: "Upscale Video",
    shortDescription: "Video -> sharper, higher-resolution video",
    longDescription: "Upscale video frames and rebuild the clip with the original audio.",
    category: "motion",
    inputMode: "single-video",
    outputMode: "video",
    status: "active",
    badge: "New",
    accepts: ["video/mp4", "video/quicktime", "video/webm", "video/x-matroska"],
    creditMode: "standard",
    generateRoute: "/api/tools/upscale-video/generate",
    ...sharedJobRoutes,
  },
  {
    id: "text-to-video",
    title: "Text to Video",
    shortDescription: "Prompt -> generated video clip",
    longDescription: "Generate a video clip directly from text prompt and settings.",
    category: "motion",
    inputMode: "text-plus-options",
    outputMode: "video",
    status: "active",
    badge: "New",
    accepts: [],
    creditMode: "standard",
    generateRoute: "/api/tools/text-to-video/generate",
    ...sharedJobRoutes,
  },
  {
    id: "text-to-voice",
    title: "Text to Voice",
    shortDescription: "Script + reference voice -> generated narration",
    longDescription: "Generate spoken audio from text using a reference voice sample.",
    category: "campaign-assets",
    inputMode: "text-plus-audio",
    outputMode: "audio",
    status: "active",
    badge: "New",
    accepts: ["audio/wav", "audio/mp3", "audio/mpeg", "audio/x-m4a", "audio/flac"],
    creditMode: "standard",
    generateRoute: "/api/tools/text-to-voice/generate",
    ...sharedJobRoutes,
  },
  {
    id: "music-generator",
    title: "Music Generator",
    shortDescription: "Prompt + lyrics -> generated song",
    longDescription: "Generate a music track with tags, lyrics and structure controls.",
    category: "campaign-assets",
    inputMode: "text-plus-options",
    outputMode: "audio",
    status: "beta",
    badge: "Beta",
    accepts: [],
    creditMode: "standard",
    generateRoute: "/api/tools/music-generator/generate",
    ...sharedJobRoutes,
  },
  {
    id: "lip-sync",
    title: "Lip Sync",
    shortDescription: "Portrait + audio -> speaking video",
    longDescription: "Create a speaking portrait video from one image and one audio file.",
    category: "avatar-tools",
    inputMode: "image-plus-audio",
    outputMode: "video",
    status: "active",
    badge: "New",
    accepts: ["image/png", "image/jpeg", "image/webp", "audio/wav", "audio/mp3", "audio/mpeg"],
    creditMode: "standard",
    generateRoute: "/api/tools/lip-sync/generate",
    ...sharedJobRoutes,
  },
  {
    id: "product-grid",
    title: "Product Grid",
    shortDescription: "1 product image -> stitched grid + tiles + selected upscale",
    longDescription: "Generate a premium 3x3 campaign grid and derivatives from one product image.",
    category: "campaign-assets",
    inputMode: "single-image",
    outputMode: "image-gallery",
    status: "active",
    badge: "Premium",
    accepts: ["image/png", "image/jpeg", "image/webp"],
    creditMode: "premium",
    creditCostNote: "This tool uses extra credits.",
    generateRoute: "/api/tools/product-grid/generate",
    ...sharedJobRoutes,
  },
  {
    id: "icon-forge",
    title: "Icon Forge",
    shortDescription: "Reference style + brand context -> 9-icon pack",
    longDescription: "Generate a branded icon set from a visual reference and brand context.",
    category: "campaign-assets",
    inputMode: "image-plus-text",
    outputMode: "image-gallery",
    status: "active",
    badge: "Premium",
    accepts: ["image/png", "image/jpeg", "image/webp"],
    creditMode: "premium",
    creditCostNote: "This tool uses extra credits.",
    generateRoute: "/api/tools/icon-forge/generate",
    ...sharedJobRoutes,
  },
  {
    id: "copywriter",
    title: "Copywriter",
    shortDescription: "Brief -> generated marketing copy",
    longDescription: "Generate ad copy, hooks or product messaging from a plain text brief.",
    category: "campaign-assets",
    inputMode: "text-only",
    outputMode: "text",
    status: "beta",
    badge: "Beta",
    accepts: [],
    creditMode: "standard",
    generateRoute: "/api/tools/copywriter/generate",
    ...sharedJobRoutes,
  },
  {
    id: "picture-to-3d",
    title: "Picture to 3D",
    shortDescription: "Image -> generated 3D mesh",
    longDescription: "Generate a 3D mesh from one reference image.",
    category: "campaign-assets",
    inputMode: "single-image",
    outputMode: "3d",
    status: "beta",
    badge: "Beta",
    accepts: ["image/png", "image/jpeg", "image/webp"],
    creditMode: "standard",
    generateRoute: "/api/tools/picture-to-3d/generate",
    ...sharedJobRoutes,
  },
];

export const toolCategories = [
  "product-visuals",
  "motion",
  "campaign-assets",
  "avatar-tools",
] as const;

export function getToolById(toolId: string) {
  return tools.find((tool) => tool.id === toolId);
}
