import type { ToolDefinition } from "@/lib/tools/types";

export const tools: ToolDefinition[] = [
  {
    id: "multi-angle-image",
    title: "8-Angle Visuals",
    shortDescription: "1 image -> 8 new campaign-ready perspectives",
    category: "product-visuals",
    inputMode: "single-image",
    outputMode: "image-gallery",
    status: "active",
    badge: "Live",
    accepts: ["image/png", "image/jpeg", "image/webp"],
  },
  {
    id: "image-to-image",
    title: "Image to Image",
    shortDescription: "1 image + prompt -> stylized image variation",
    category: "product-visuals",
    inputMode: "single-image",
    outputMode: "image-gallery",
    status: "active",
    badge: "Live",
    accepts: ["image/png", "image/jpeg", "image/webp"],
  },
  {
    id: "product-grid",
    title: "Product Grid",
    shortDescription: "1 product image -> stitched grid + tiles + upscale",
    category: "campaign-assets",
    inputMode: "single-image",
    outputMode: "image-gallery",
    status: "active",
    badge: "Premium",
    premium: true,
    extraCredits: true,
    creditNote: "This tool consumes extra credits.",
    accepts: ["image/png", "image/jpeg", "image/webp"],
  },
  {
    id: "six-frame-video",
    title: "6-Frame Motion",
    shortDescription: "6 frames -> 1 stylized video",
    category: "motion",
    inputMode: "multi-image-sequence",
    outputMode: "video",
    status: "active",
    badge: "Live",
    accepts: ["image/png", "image/jpeg", "image/webp"],
  },
  {
    id: "image-to-video",
    title: "Image to Video",
    shortDescription: "1 image + prompt -> animated video shot",
    category: "motion",
    inputMode: "single-image",
    outputMode: "video",
    status: "active",
    badge: "New",
    accepts: ["image/png", "image/jpeg", "image/webp"],
  },
  {
    id: "lip-sync",
    title: "Lip Sync",
    shortDescription: "Portrait + audio -> speaking video",
    category: "avatar-tools",
    inputMode: "image-plus-audio",
    outputMode: "video",
    status: "active",
    badge: "Live",
    accepts: ["image/png", "image/jpeg", "image/webp", "audio/mpeg", "audio/wav"],
  },
  {
    id: "text-to-video",
    title: "Text to Video",
    shortDescription: "Prompt -> cinematic video generation",
    category: "motion",
    inputMode: "text",
    outputMode: "video",
    status: "coming-soon",
    badge: "Soon",
    accepts: [],
  },
  {
    id: "infinite-talk",
    title: "Infinite Talk",
    shortDescription: "Avatar loop for long-form talking shots",
    category: "avatar-tools",
    inputMode: "mixed",
    outputMode: "video",
    status: "coming-soon",
    badge: "Soon",
    accepts: [],
  },
  {
    id: "scene-variants",
    title: "Scene Variants",
    shortDescription: "1 source -> multiple new campaign scenes",
    category: "campaign-assets",
    inputMode: "single-image",
    outputMode: "image-gallery",
    status: "coming-soon",
    badge: "Soon",
    accepts: ["image/png", "image/jpeg", "image/webp"],
  },
];

export const toolCategories = [
  "product-visuals",
  "motion",
  "campaign-assets",
  "avatar-tools",
];

export function getToolById(toolId: string) {
  return tools.find((tool) => tool.id === toolId);
}
